### ISSUE TITLE
Update GRIB API

### ISSUE THREAD

**Issue by rhattersley** [SciTools/conda-recipes-scitools#146]
... to at least 1.13

See https://github.com/SciTools/iris/pull/1913#issuecomment-173241939

**Comment by rhattersley** [comment]
Ping @marqh

**Comment by marqh** [comment]
so we are ready to go with a GRIB 14.2
#136 
we just need to update the iris conda requirements and iris build

However, I still have a test failure mode to fix in iris to get us over the line
https://github.com/SciTools/iris/issues/1891

nearly there

**Comment by rhattersley** [comment]
> we are ready to go with a GRIB 14.2
> #136

Super, thanks ... I was looking for "1.<13|14>", the "14.2" made me overlook it.
