### ISSUE TITLE
cartopy v0.14 not building on OSX

### ISSUE THREAD

**Issue by marqh** [SciTools/conda-recipes-scitools#203]
I have put the minimum cartopy requirement for the Iris recipe to v0.13
#202

I wanted to put 14, but when I do this, the build for osx fails as cartopy 0.14 doesn't build on OSX, but 13 has been built

not sure why this is, it should be tracked down

**Comment by marqh** [comment]
potential clue regarding this
https://github.com/SciTools/conda-recipes-scitools/blob/master/cartopy/meta.yaml#L24
```
    # On OSX We need to effectively pin the geos version to the
    # one used by the specific shapely being targetted (we're letting
    # conda's package solver will deal with that).
```

**Comment by pelson** [comment]
Closed due to the deprecation of this repo. #250
