### ISSUE TITLE
Unpin conda-build 2.0.10

### ISSUE THREAD

**Issue by lbdreyer** [SciTools/conda-recipes-scitools#221]
We have pinned to conda-build 2.0.10 (see https://github.com/SciTools/conda-recipes-scitools/pull/220) due to a change introduced in conda-build 2.0.11 that does not work with conda-build-all. 
Once conda-build-all is fixed (see https://github.com/SciTools/conda-build-all/pull/71) this should be unpinned.

**Comment by pelson** [comment]
Closed due to the deprecation of this repo. #250
