### ISSUE TITLE
PaddingError: Placeholder of length '80' too short in package scitools::udunits2-2.2.20-0.

### ISSUE THREAD

**Issue by dkillick** [SciTools/conda-recipes-scitools#226]
Raising here on behalf of @jeixav (see https://github.com/SciTools/iris/issues/2293):

> I am trying to install Iris using Conda:
> `conda install -c scitools iris`
> The installation fails with this message:
>> PaddingError: Placeholder of length '80' too short in package scitools::udunits2-2.2.20-0.
>> The package must be rebuilt with conda-build > 2.0.
>
> I think a similar error is described in this issue: conda/conda#4088. Is the error message accurate, was udunits built with conda-build < 2.0? Could the SciTools team rebuild the udunits2 package with conda-build > 2.0?
>To reproduce this error, the Miniconda path must be long. I used: >/tmp/armnkro/35722/tmp.rTJtNvkKDZ/fca90fd2-159d-47d7-9593-45f5bd5e9a45/miniconda2.

**Comment by dkillick** [comment]
Again, thanks for pointing us to this issue @jeixav. There are some options you could follow as workarounds:

* the obvious workaround is you could shorten your prefix path if possible, however I am well aware that this suggestion might simply not be possible in your case. Or...
* you could use the `conda-forge` channel instead (but note that the most recent version of Iris built on that channel is v1.11.0). If this is a problem, you _might_ be able to get udunits2 from the `conda-forge` channel and everything else from the `scitools` channel, and it might just work. Note that in general we do not recommend mixing channels, but sometimes needs must! 

> Could the SciTools team rebuild the udunits2 package with conda-build > 2.0?

As it happens, I am actually working on updating the version of udunits2 that we provide in the `scitools` channel, and it looks like our build process has now been updated to use conda-build > v2.0, which should fix this for you. I'll keep you updated...

**Comment by jeixav** [comment]
Thank you for providing support @dkillick. I will test Iris from the conda-forge channel.

**Comment by pelson** [comment]
Closed due to the deprecation of this repo. #250
