### ISSUE TITLE
ecmwf_grib: build with fortran support

### ISSUE THREAD

**Issue by ajdawson** [SciTools/conda-recipes-scitools#55]
Could building ECMWF's GRIB API with support for fortran be considered? Currently the build is configured with the `--disable-fortran` option. I understand that Iris only depends upon the C portion of the API, but other packages might be able to use the fortran interface. For example I want to install [ectransforms](https://bitbucket.org/ajdawson/ectransforms) in the same conda env as Iris, and it would be convenient for me to be able to use the same GRIB API for both (ectransforms depends on EMOSLIB, which in turn depends of the fortran GRIB API interface).

**Comment by pelson** [comment]
:+1: - sounds reasonable to me provided there isn't a major maintenance overhead. Do you want to make a PR @ajdawson?

**Comment by esc24** [comment]
I've been meaning to do a new build to incorporate a couple of fixes for OSX that went into conda-build. I'll be happy to do some testing on OSX if it helps.

**Comment by ajdawson** [comment]
@esc24 - I think that would be useful. I probably won't have time to get to this particularly soon. I only have 32/64-bit Linux at my disposal, so I cannot do anything about OS X anyway.

I believe all that is really necessary should be:

(0. Access to a fortran compiler.)
1. Remove the flag on the configure command that explicitly disables the fortran interface, `--disable-fortran`.
2. Additionaly set `FFLAGS="-fPIC"` to the configure command in build.sh. Essentially it should reflect the same options you want for the C compiler, so perhaps `"FFLAGS=-fPIC -I$PREFIX/include"` would be better, I'm not sure. I didn't use this when building locally in a conda env but I guess there is a good reason you set this in `CFLAGS` for the recipe.

**Comment by ajdawson** [comment]
Closing due to lack of interest, and because this lags behind the current technology for packaging.

**Comment by pelson** [comment]
> Closing due to lack of interest, and because this lags behind the current technology for packaging.

That is fair. I think we could reasonably put this into conda-forge.

**Comment by ajdawson** [comment]
I'm not actually sure it is even a good idea at the moment! If it is I will raise in conda-forge. Cheers.
