### ISSUE TITLE
Specify forward compatible numpy dependencies?

### ISSUE THREAD

**Issue by shoyer** [SciTools/conda-recipes-scitools#59]
If we used something like this:
```
build:
    numpy =1.8

run:
    numpy >=1.8
```

Then I think cartopy, etc., built on numpy 1.8 could be installed on numpy 1.9. For what it's worth, I've found that the current builds of cartopy up on Binstar work fine when installed with numpy 1.9, though multiple installs are required to make that happen with the current packages.

See this mailing list thread for more details:
https://groups.google.com/a/continuum.io/forum/#!topic/conda/_GbIcpBvs5g

**Comment by pelson** [comment]
Nice idea. Though I guess the version isn't really necessary at all. I'd be tempted to try just removing it and letting the fact that cfchecker does actually depend on <=1.8 control the numpy version which gets used.

**Comment by shoyer** [comment]
Well, some scitools packages (e.g., Cartopy) use the NumPy ABI, which is not guaranteed to be forwards compatible. That means that if you build with numpy version X, Cartopy binaries may not work with numpy versions <X. So you do need some way of ensuring that minimum required numpy version.

**Comment by ThomasLecocq** [comment]
Hey!

this is really an annoying thing... (together with https://github.com/SciTools/cartopy/issues/595)... could you release a fixed version ?

**Comment by pelson** [comment]
So the scitools channel now does this correctly (though perhaps overly [conservatively](https://github.com/SciTools/conda-recipes-scitools/blob/master/cartopy/meta.yaml#L22)...)

Just ```conda update -c scitools cartopy``` and you should get the latest version against the latest numpy.

@shoyer - I think that just about covers it. Do you agree? I'd be happy to reduce the conservatism on the cartopy recipe, if your interested in submitting?

**Comment by shoyer** [comment]
I agree, I think this issue is fixed now!
