### ISSUE TITLE
Python 3 packages

### ISSUE THREAD

**Issue by QuLogic** [SciTools/conda-recipes-scitools#75]
Please provide Python 3 conda packages for all items that support it. It is currently impossible to even attempt converting `iris` to Python 3 with conda as pretty much all dependencies are not available in the `scitools` (or `ioos`) channel.

**Comment by pelson** [comment]
Agreed. The current build process makes this a little hard. I'm working on an alternative which will allow us to have a full build matrix (np versions, py versions etc.).

**Comment by ocefpaf** [comment]
@QuLogic I would love to provide Python 3 versions for the IOOS packages.  Sadly most of our stack is not ready yet (and maybe they will never be :unamused:).

**Comment by QuLogic** [comment]
OWSLib is now available for Python 3 as well, but not tested since there's no conda package yet.

**Comment by QuLogic** [comment]
> Sadly most of our stack is not ready yet

@ocefpaf Which ones do you mean exactly?

**Comment by ocefpaf** [comment]
@QuLogic I was refering to the `ioos` channel.

**Comment by pelson** [comment]
OK, I've moved this forwards significantly in the last few days. #86 refers.

**Comment by pelson** [comment]
On the travis-ci Linux image, the following are now being built:

```
	biggus-0.10.0-nppy27_2 (will be built: False)
	biggus-0.10.0-nppy34_2 (will be built: False)
	cdat-lite-5.2.1-py27_2 (will be built: False)
	geos-3.4.2-2 (will be built: False)
	jasper-1.900.1-2 (will be built: False)
	libmo_unpack-3.0-0 (will be built: False)
	mo_pack-0.2.0-np19py27_1 (will be built: False)
	mo_pack-0.2.0-np18py34_1 (will be built: False)
	mo_pack-0.2.0-np19py34_1 (will be built: False)
	mo_pack-0.2.0-np18py27_1 (will be built: False)
	proj4-4.9.1-0 (will be built: False)
	pyepsg-0.2.0-py27_0 (will be built: False)
	pyepsg-0.2.0-py34_0 (will be built: False)
	pyke-1.1.1-py27_0 (will be built: False)
	pyke-1.1.1-py34_0 (will be built: False)
	pyshp-1.2.1-py27_0 (will be built: False)
	pyshp-1.2.1-py34_0 (will be built: False)
	python-dateutil-2.2-py27_0 (will be built: False)
	python-dateutil-2.2-py34_0 (will be built: False)
	pyugrid-0.1.1-nppy27_1 (will be built: False)
	shapely-1.5.8-np19py27_2 (will be built: False)
	shapely-1.5.8-np18py34_2 (will be built: False)
	shapely-1.5.8-np19py34_2 (will be built: False)
	shapely-1.5.8-np18py27_2 (will be built: False)
	udunits-2.2.17-4 (will be built: False)
	cf_units-0.1.0-nppy27_1 (will be built: False)
	cfchecker-2.0.5-np18py27_1 (will be built: False)
	ecmwf_grib-1.12.1-np19py27_3 (will be built: False)
	ecmwf_grib-1.12.1-np18py34_3 (will be built: False)
	ecmwf_grib-1.12.1-np19py34_3 (will be built: False)
	ecmwf_grib-1.12.1-np18py27_3 (will be built: False)
	owslib-0.9.0-py27_0 (will be built: False)
	owslib-0.9.0-py34_0 (will be built: False)
	cartopy-0.13.0-np19py27_0 (will be built: False)
	cartopy-0.13.0-np18py34_0 (will be built: False)
	cartopy-0.13.0-np19py34_0 (will be built: False)
	cartopy-0.13.0-np18py27_0 (will be built: False)
	iris-1.8.0-nppy27_1 (will be built: False)
```

The conditions within the recipes now need to be updated wherever necessary (e.g. removal of https://github.com/SciTools/conda-recipes-scitools/blob/master/iris/meta.yaml#L14 when we can build iris and its deps on py 3).
