### ISSUE TITLE
Build error with ecmwf_grib Python 3 (conda build)

### ISSUE THREAD

**Issue by groutr** [SciTools/conda-recipes-scitools#80]
Building ecmwf_grib package on OS X with Python 3.4 results in a linking error.  It looks like one of the linking flags is used incorrectly.  Building with Python 2 works without problems.
```
libtool: link: gcc -Wl,-undefined -Wl,dynamic_lookup -o .libs/_gribapi_swig.so -bundle  .libs/gribapi_swig_wrap.o .libs/grib_interface.o   -framework CoreFoundation -L/Users/rgrout/miniconda/envs/_build_placehold_placehold_placehold_placehold_plac/lib -L/Users/rgrout/miniconda/envs/_build_placehold_placehold_placehold_placehold_plac/lib/lib ../src/.libs/libgrib_api.dylib -lpython3.4m -ldl /Users/rgrout/miniconda/envs/_build_placehold_placehold_placehold_placehold_plac/lib/libjasper.dylib -lm  -Wl,-stack_size -Wl,1000000 -Wl,-rpath -Wl,/Users/rgrout/miniconda/envs/_build_placehold_placehold_placehold_placehold_plac/lib   -framework CoreFoundation
ld: warning: directory not found for option '-L/Users/rgrout/miniconda/envs/_build_placehold_placehold_placehold_placehold_plac/lib/lib'
ld: -stack_size option can only be used when linking a main executable
collect2: error: ld returned 1 exit status
make[1]: *** [_gribapi_swig.la] Error 1
make: *** [all-recursive] Error 1
```

**Comment by groutr** [comment]
It looks like the ```-stack_size``` flag is coming python-config in the ecmwf conda recipe.

**Comment by pelson** [comment]
Ping @QuLogic - any ideas?

**Comment by QuLogic** [comment]
I don't know much about OS X, but everything I can find seems to indicate this is a bug in Python 3.4 (e.g., [this anaconda report](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/iF0OdFLIQgU), [this GTK OSX patch](https://github.com/GNOME/gtk-osx/blob/master/patches/Python3.4-stack_size-flag.patch)).

**Comment by pelson** [comment]
Woops. I've just duplicated this in #88.

**Comment by pelson** [comment]
I don't think there will ever be a GRIB_API for py3k. Looks like it has been superseded by the ecCodes project, which looks like a bit of re-labelling of the grib_api with some functionality added.

I'll close this issue, as we are essentially in need of investigating ecCodes.
