### ISSUE TITLE
Handle AppVeyor's new(ish) Cygwin image

### ISSUE THREAD

**Issue by pelson** [SciTools/conda-recipes-scitools#82]
As per @ocefpaf's change in https://github.com/ioos/conda-recipes/pull/252/files#diff-180360612c6b8c4ed830919bbb4dd459R27, we need to handle the git that is being shipped with Cygwin - it is stopping out builds from working on Windows.

**Comment by pelson** [comment]
I suspect it has been fixed on appveyor's end.

**Comment by ocefpaf** [comment]
Nope on conda's end.  It turns out this was a conda bug that got fixed in a massive commit some time ago.  If I ever find the commit hash I'll paste it here for reference.

**Comment by ocefpaf** [comment]
Found it: https://github.com/asmeurer/conda-build/commit/1c6f5c2f617eeab3b70bdb2a62cc0dcf7d7ae797

**Comment by pelson** [comment]
Aha. Thanks @ocefpaf!
